---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mrjrbzrhwqsa/public_html/lekkerdicht/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp praktisch.html $DEPLOYPATH
    - /bin/cp contactform.php $DEPLOYPATH
    - /bin/cp -r * $DEPLOYPATH
    
